In [5]:
#opening a file an reading it
with open('employees.txt',"r") as file:
    print(file.read())

Benny
Beno
Bright

In [4]:
#writing something into that file;
with open('employees.txt',"w")as file:
    file.write("Benny\nBeno\nBright")

In [4]:
#adding employees to the list of employees:
with open('employees.txt',"a")as file:
    file.write("\ndavid")

In [17]:
class Employee_mangement_system:
    def view_employees():
        with open('employees.txt',"r") as file:
            print(file.read())
    def add_employees(name):
        with open('employees.txt',"a")as file:
            file.write(name)

In [21]:
Employee_mangement_system.view_employees()

Bewin
Beno
Bright
davidsona
sona

In [20]:
Employee_mangement_system.add_employees('\nsona')

In [53]:
class Employee:
    list_of_employees=[]
    @staticmethod
    def add_employeess():
        n=int(input('enter the no of employes to add:'))
        for i in range(n):
            name=input('enter the name of employee:')
            if name.strip()!="":
                Employee.list_of_employees.append(name)
            else:
                print('Give a correct name for employee')
        return Employee.list_of_employees   
    @staticmethod
    def view_employeess():
        for i in range(len(Employee.list_of_employees)):
            print(f'Employee{i+1}:{Employee.list_of_employees[i]}')

In [51]:
Employee.add_employeess()

enter the no of employes to add: 1
enter the name of employee: david

['david']

In [55]:
Employee.view_employeess()

In [44]:
list_employees

NameError: name 'list_employees' is not defined

In [79]:
class Employee_management_system:
    def __init__(self,username,password):
        self.username= username
        self.password=password

    def add_employee(self):
        print(f'choice selected: Adding employees.., please enter username and password to proceed.')
        if (self.username=="admin" and self.password==1212):
            n=int(input("enter the no.of employees to add: "))
            with open("employees.txt","a") as file:
                for i in range(n):
                    name=input('enter the name of the employee:')
                    file.write("\n"+name)
        else:
            print('Incorrect password')
    def view_employees(self):
        print(f'choice selected: Viewing all employees..')
        if (self.username=="admin" and self.password==1212):
            with open("employees.txt","r") as file:
                print(file.read())
        else:
            print('Incorrect password')
    def overwrite_employee(self):
        print(f'choice selected: Clearing all employees and adding new set of employees..')
        print(f'Are you sure want to clear all employee names and add new ones?')
        Yes_or_No= input('enter Yes or No:')
        if Yes_or_No.lower()=='yes':
            if (self.username=="admin" and self.password==1212):
                n=int(input("enter the no.of employees to add: "))
                with open("employees.txt","w") as file:
                    for i in range(n):
                        name=input('enter the name of the employee:')
                        file.write("\n"+name)
            else:
                print('Incorrect password')
        else:
            print('Ok, Thanks for confirmation')

In [80]:
username=input("enter the username: ")
password=int(input('enter the password: '))
obj=Employee_management_system(username,password)
print(f'1. Add employees')
print(f'2. View employees')
print(f'3. Clear all employees and overwrite all employees')
choice=int(input('enter a choice 1 to 3: '))

if choice==1:
    obj.add_employee()
elif choice ==2:
    obj.view_employees()
elif choice==3:
    obj.overwrite_employee()
else:
    print("enter correct option between 1 to 3")

enter the username:  admin
enter the password:  1212

1. Add employees
2. View employees
3. Clear all employees and overwrite all employees

enter a choice 1 to 3:  2

choice selected: Viewing all employees..

Bewin
Beno
Mummy
daddy
david

In [1]:
import pandas as pd

In [20]:
df1=pd.read_excel(r"C:\Users\Lenovo\Documents\Jupiter code files\Book1.xlsx")
df1.head()
df1.rename(columns={'Bewin':'Name',22:'Age',25000:'Salary','DT Team':'Team'})

Empty DataFrame
Columns: [Name, Age, Salary, Team]
Index: []

In [6]:
df.columns

Index(['Name', 'Age', 'Salary', 'Team'], dtype='object')

In [5]:
df.columns=['Name','Age','Salary','Team']

In [8]:
df.head()

Empty DataFrame
Columns: [Bewin, 22, 25000, DT Team]
Index: []

In [11]:
df.rename(columns={'Bewin':'Name',22:'Age',25000:'Salary','DT Team':'Team'})

Empty DataFrame
Columns: [Name, Age, Salary, Team]
Index: []

enter name of employee:  Bewin
enter the age of employee:  22
enter the salary:  200000
enter the team name:  DT

0

In [15]:
df.head()

   Bewin  22   25000 DT Team
0  Bewin  22  200000      DT

In [16]:
df=pd.DataFrame(columns=['Name',"Age",'Salary','Team'])

In [17]:
Name=input('enter name of employee: ')
Age=int(input('enter the age of employee: '))
Salary=int(input('enter the salary: '))
Team=input('enter the team name: ')
print(len(df))
df.loc[len(df)]=[Name,Age,Salary,Team]

enter name of employee:  Bewin
enter the age of employee:  22
enter the salary:  200000
enter the team name:  DT Team

0

In [18]:
df.head()

    Name  Age  Salary     Team
0  Bewin   22  200000  DT Team

In [21]:
class Employee_management_system:
    def __init__(self,username,password):
        self.username= username
        self.password=password

    def add_employee_and_details(self):
        print(f'choice selected: Adding employees.., please enter username and password to proceed.')
        if (self.username=="admin" and self.password==1212):
            n=int(input("enter the no.of employees to add: "))
            for i in range(n):
                Name=input('enter name of employee: ')
                Age=int(input('enter the age of employee: '))
                Salary=int(input('enter the salary: '))
                Team=input('enter the team name: ')
                print(len(df))
                df.loc[len(df)]=[Name,Age,Salary,Team]
        else:
            print('Incorrect password')
    def view_employees(self):
        print(f'choice selected: Viewing all employees..')
        if (self.username=="admin" and self.password==1212):
            n=len(df)
            df.head(n)
        else:
            print('Incorrect password')
    def Clear_employee(self):
        print(f'choice selected: Clearing all employees ')
        print(f'Are you sure want to clear all employee names ')
        Yes_or_No= input('enter Yes or No:')
        if Yes_or_No.lower()=='yes':
            if (self.username=="admin" and self.password==1212):
                df=df.loc[0:0]
            else:
                print('Incorrect password')
        else:
            print('Ok, Thanks for confirmation')

In [23]:
username=input("enter the username: ")
password=int(input('enter the password: '))
obj=Employee_management_system(username,password)
print(f'1. Add employees')
print(f'2. View employees')
print(f'3. Clear all employees ')
choice=int(input('enter a choice 1 to 3: '))

if choice==1:
    obj.add_employee_and_details()
elif choice ==2:
    obj.view_employees()
elif choice==3:
    obj.overwrite_employee()
else:
    print("enter correct option between 1 to 3")

enter the username:  admin
enter the password:  1212

1. Add employees
2. View employees
3. Clear all employees

enter a choice 1 to 3:  1

choice selected: Adding employees.., please enter username and password to proceed.

enter the no.of employees to add:  1
enter name of employee:  Beno
enter the age of employee:  26
enter the salary:  300000
enter the team name:  GSK

1

In [25]:
df.head()

    Name  Age  Salary     Team
0  Bewin   22  200000  DT Team
1   Beno   26  300000      GSK